name: adopte_un_candidat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed: ^2.5.2
  riverpod: ^2.5.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  shared_preferences: ^2.0.8
  go_router: ^14.1.2
  firebase_storage: ^12.0.0
  image_picker: ^1.1.1
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  cupertino_icons: ^1.0.8
  line_icons: ^2.0.2
  async: ^2.11.0
  appinio_swiper: ^2.1.1
  flutter_card_swiper: ^7.0.1
  google_fonts: ^6.2.1
  firebase_app_check: ^0.3.0
  firebase_core_platform_interface: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
      - asset: fonts/Quicksand-Medium.ttf
    - family: Roboto
      fonts:
      - asset: fonts/Roboto-Regular.ttf