name: adopte_un_candidat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.5.2
  riverpod: ^2.5.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  shared_preferences: ^2.0.8
  go_router: ^14.1.2
  firebase_storage: ^11.7.5
  image_picker: ^1.1.1
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
