// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1t4q-CkewyOoSiFGGIdd7xfGfSZ6vb0',
    appId: '1:1020480123168:web:8b57518a827b59df06a745',
    messagingSenderId: '1020480123168',
    projectId: 'adopte-un-candidat',
    authDomain: 'adopte-un-candidat.firebaseapp.com',
    storageBucket: 'adopte-un-candidat.appspot.com',
    measurementId: 'G-LR1KHFSL6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApvBVc_j9fQYxGnqDAGRRKRSXowDW9umo',
    appId: '1:1020480123168:android:d361e6eca257d2d006a745',
    messagingSenderId: '1020480123168',
    projectId: 'adopte-un-candidat',
    storageBucket: 'adopte-un-candidat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUKKX3H30HmBupIWRtcQdfOppzXZaeeGw',
    appId: '1:1020480123168:ios:e8f3bc2bec06d41406a745',
    messagingSenderId: '1020480123168',
    projectId: 'adopte-un-candidat',
    storageBucket: 'adopte-un-candidat.appspot.com',
    iosBundleId: 'com.example.adopteUnCandidat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUKKX3H30HmBupIWRtcQdfOppzXZaeeGw',
    appId: '1:1020480123168:ios:e8f3bc2bec06d41406a745',
    messagingSenderId: '1020480123168',
    projectId: 'adopte-un-candidat',
    storageBucket: 'adopte-un-candidat.appspot.com',
    iosBundleId: 'com.example.adopteUnCandidat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ1t4q-CkewyOoSiFGGIdd7xfGfSZ6vb0',
    appId: '1:1020480123168:web:e49fb223cae1447406a745',
    messagingSenderId: '1020480123168',
    projectId: 'adopte-un-candidat',
    authDomain: 'adopte-un-candidat.firebaseapp.com',
    storageBucket: 'adopte-un-candidat.appspot.com',
    measurementId: 'G-32KLN223Z6',
  );
}
