
final List<String> items = [
  'administration et gestion',
  'secrétariat',
  'services généraux',
  'gestion de projets',
  'recrutement',
  'formation et développement',
  'gestion des salaires et des avantages sociaux',
  'relations avec les employés',
  'santé et sécurité au travail',
  'gestion des talents',
  'développement organisationnel',
  'comptabilité générale',
  'comptabilité analytique',
  'contrôle de gestion',
  'trésorerie',
  'audit interne',
  'gestion des risques financiers',
  'planification financière',
  'fiscalité',
  'marketing stratégique',
  'marketing opérationnel',
  'communication interne et externe',
  'publicité',
  'relations publiques',
  'études de marché',
  'gestion de la marque',
  'marketing digital',
  'content marketing',
  'relations avec les médias',
  'force de vente',
  'gestion des comptes clés',
  'support commercial',
  'service après-vente',
  'développement des affaires',
  'gestion des relations clients (CRM)',
  'stratégie de vente',
  'gestion de la production',
  'qualité',
  'maintenance',
  'logistique et supply chain',
  'gestion des stocks',
  'planification de la production',
  'contrôle de la qualité',
  'amélioration continue',
  'recherche fondamentale',
  'développement de produits',
  'innovation',
  'prototypage',
  'veille technologique',
  'tests et essais',
  'développement et maintenance des systèmes d\'information',
  'support informatique',
  'sécurité informatique',
  'gestion des données',
  'administration réseau',
  'développement de logiciels',
  'gestion de projets IT',
  'infrastructure IT',
  'gestion des achats',
  'négociation avec les fournisseurs',
  'logistique des achats',
  'évaluation des fournisseurs',
  'gestion des contrats',
  'conseils juridiques',
  'conformité réglementaire',
  'gestion des risques',
  'propriété intellectuelle',
  'règlement des litiges',
  'gouvernance d\'entreprise',
  'assistance clientèle',
  'gestion des réclamations',
  'satisfaction client',
  'support technique',
  'fidélisation des clients',
  'centres d\'appels',
  'gestion de l\'impact environnemental',
  'initiatives sociales',
  'communication sur les pratiques durables',
  'gestion des ressources naturelles',
  'programmes de responsabilité sociétale',
  'planification stratégique',
  'gestion des projets',
  'fusions et acquisitions',
  'analyse concurrentielle',
  'expansion internationale',
  'développement de nouvelles activités',
  'sécurité au travail',
  'gestion des risques sanitaires',
  'prévention des accidents',
  'sécurité incendie',
  'communication financière',
  'gestion des relations avec les actionnaires',
  'rapports financiers',
  'assemblées générales',
  'gestion des transports',
  'optimisation des flux logistiques',
  'gestion des entrepôts',
  'distribution',
  'entretien des bâtiments',
  'sécurité des installations',
  'gestion de l\'énergie',
  'services aux occupants',
  'support administratif',
  'gestion documentaire',
  'coordination des services internes',
  'design produit',
  'design graphique',
  'conception UX/UI',
  'création de contenu visuel',
  'lobbying',
  'relations gouvernementales',
  'affaires publiques',
  'gestion de la documentation',
  'partage des connaissances',
  'formation continue',
  'audit financier',
  'audit opérationnel',
  'contrôle des processus',
  'gestion des idées',
  'programmes d\'innovation',
  'collaboration avec les start-ups',
  'planification de la continuité des activités',
  'gestion des situations d\'urgence',
  'communication de crise'
];

final List<String> items2 = [
  'contrat à durée indéterminée (CDI)',
  'contrat à durée déterminée (CDD)',
  'contrat de travail temporaire (intérim)',
  'contrat d\'apprentissage',
  'contrat de professionnalisation',
  'contrat à temps partiel',
  'contrat de travail intermittent',
  'contrat saisonnier',
  'contrat d\'insertion',
  'contrat d\'accompagnement dans l\'emploi (CAE)',
  'contrat initiative emploi (CIE)',
  'contrat d\'avenir',
  'contrat unique d\'insertion (CUI)',
  'contrat de mission',
  'contrat de stage',
  'contrat freelance',
  'contrat d\'agent commercial',
  'contrat de prestation de services',
  'contrat de mise à disposition',
  'contrat de sous-traitance',
  'contrat de franchise',
  'contrat de partenariat',
  'contrat de joint-venture',
  'contrat de consultant',
  'contrat d\'entrepreneur individuel',
  'contrat de portage salarial'
];

final List<String> items3 = [
  'Mensuels',
  'Horaires',
  'Mission',
  'Autre',
];